# Generated by Django 5.1.5 on 2025-02-19 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0004_alter_containerunloadingzone2inspection_defect_description"),
        ("users", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="defect",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="supplies.containerunloadingzonesbinspection",
            ),
        ),
    ]
