# Generated by Django 5.1.7 on 2025-04-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_notification_defect"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpdeskContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(max_length=255, verbose_name="Должность"),
                ),
                (
                    "employee_name",
                    models.CharField(max_length=255, verbose_name="Сотрудник"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=50, verbose_name="Мобильный"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("department", models.CharField(max_length=255, verbose_name="Отдел")),
            ],
            options={
                "verbose_name": "Контакт справочного отдела",
                "verbose_name_plural": "Контакты справочного отдела",
            },
        ),
    ]
