# Generated by Django 5.1.7 on 2025-04-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_helpdeskcontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helpdeskcontact",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-mail"
            ),
        ),
    ]
