# Generated by Django 5.1.7 on 2025-04-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_helpdeskcontact_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="vin_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
