# Generated by Django 5.1.7 on 2025-04-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_notification_vin_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="patronymic",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Отчество"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="Фамилия"),
        ),
    ]
