# Generated by Django 5.1.7 on 2025-05-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_customuser_patronymic_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("controller", "Контролер"),
                    ("master", "Мастер"),
                    ("admin", "Администратор"),
                    ("qrr_specialist", "QRR специалист"),
                    ("qrr_supervisor", "QRR начальник участка"),
                    ("qrr_shift_lead", "QRR начальник смены"),
                ],
                default="controller",
                max_length=20,
            ),
        ),
    ]
