# Generated by Django 5.1.7 on 2025-06-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_employee_alter_customuser_role_exporthistory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="selection",
            name="hours",
            field=models.PositiveIntegerField(default=8, verbose_name="Часы"),
        ),
        migrations.AddField(
            model_name="selection",
            name="is_xtk",
            field=models.BooleanField(default=False, verbose_name="ХТК"),
        ),
        migrations.AlterUniqueTogether(
            name="selection",
            unique_together={("manager", "employee", "selected_date")},
        ),
    ]
