# Generated by Django 5.1.7 on 2025-06-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_selection_hours_selection_is_xtk_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exporthistory",
            options={
                "ordering": ["-export_date"],
                "verbose_name_plural": "История экспортов",
            },
        ),
        migrations.AddField(
            model_name="selection",
            name="justification",
            field=models.TextField(blank=True, null=True, verbose_name="Обоснование"),
        ),
    ]
