# Generated by Django 5.1.7 on 2025-06-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_exporthistory_options_selection_justification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("controller", "Контролер"),
                    ("master", "Мастер"),
                    ("head_area", "Начальник участка"),
                    ("admin", "Администратор"),
                    ("qrr_specialist", "QRR специалист"),
                    ("qrr_supervisor", "QRR начальник участка"),
                    ("qrr_shift_lead", "QRR начальник смены"),
                    ("dp", "Делопроизводитель"),
                ],
                default="controller",
                max_length=20,
            ),
        ),
    ]
