# Generated by Django 5.1.7 on 2025-06-30 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_customuser_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="selection",
            name="end_time",
            field=models.TimeField(
                default=datetime.time(16, 30), verbose_name="Окончание работы"
            ),
        ),
        migrations.AddField(
            model_name="selection",
            name="start_time",
            field=models.TimeField(
                default=datetime.time(7, 30), verbose_name="Начало работы"
            ),
        ),
    ]
