# Generated by Django 5.1.7 on 2025-07-04 08:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_selection_end_time_selection_start_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="OvertimeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField(default=datetime.time(7, 30))),
                ("end_time", models.TimeField(default=datetime.time(16, 30))),
                ("hours", models.PositiveIntegerField(default=8)),
                (
                    "justification",
                    models.TextField(blank=True, null=True, verbose_name="Обоснование"),
                ),
                ("is_xtk", models.BooleanField(default=False, verbose_name="ХТК")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.employee"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("employee", "date")},
            },
        ),
    ]
