# Generated by Django 5.1.7 on 2025-07-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_overtimerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="overtimerecord",
            name="compensated_day",
            field=models.DateField(
                blank=True, null=True, verbose_name="День отгула (за переработку)"
            ),
        ),
    ]
