# Generated by Django 5.1.7 on 2025-07-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_overtimerecord_compensated_day"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="selection",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="selection",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="overtimerecord",
            name="compensation_type",
            field=models.CharField(
                choices=[("payment", "Оплата"), ("day_off", "Отгул")],
                default="payment",
                max_length=10,
                verbose_name="Тип компенсации",
            ),
        ),
        migrations.AddField(
            model_name="selection",
            name="compensated_day",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата отгула (если отгул)"
            ),
        ),
        migrations.AddField(
            model_name="selection",
            name="compensation_type",
            field=models.CharField(
                choices=[("payment", "Оплата"), ("day_off", "Отгул")],
                default="payment",
                max_length=10,
                verbose_name="Тип компенсации",
            ),
        ),
        migrations.AlterField(
            model_name="overtimerecord",
            name="compensated_day",
            field=models.DateField(
                blank=True, null=True, verbose_name="День отгула (если выбран)"
            ),
        ),
    ]
