# Generated by Django 5.1.7 on 2025-07-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_alter_selection_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="selection",
            options={"ordering": ["-selected_date"]},
        ),
        migrations.RemoveField(
            model_name="overtimerecord",
            name="compensation_type",
        ),
        migrations.AlterUniqueTogether(
            name="selection",
            unique_together={("manager", "employee", "selected_date")},
        ),
        migrations.AlterField(
            model_name="overtimerecord",
            name="compensated_day",
            field=models.DateField(
                blank=True, null=True, verbose_name="День отгула (за переработку)"
            ),
        ),
        migrations.RemoveField(
            model_name="selection",
            name="compensated_day",
        ),
        migrations.RemoveField(
            model_name="selection",
            name="compensation_type",
        ),
    ]
