# Generated by Django 5.1.7 on 2025-09-06 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_selection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('rvd', 'Доступ к сайту РВД'), ('dp', 'Доступ к сайту для делопроизводителя'), ('employee_contact_directory', 'Доступ к справчонику сотрудников'), ('employee_shift_management_vqa', 'Доступ к управлению сменой VQA'), ('employee_shift_management_pqa', 'Доступ к управлению сменой PQA'), ('vqa_data_management', 'Доступ к управлению данными VQA'), ('vin_tracking', 'Доступ к сайту отслеживания по VIN'), ('pqa_dashboard', 'Доступ к дэшборду PQA'), ('vqa_dashboard', 'Доступ к дэшборду VQA')]},
        ),
        migrations.CreateModel(
            name='KTVDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_type', models.CharField(choices=[('by_grades', 'По грейдам'), ('by_mass', 'По массовости')], max_length=20, verbose_name='Источник таблицы')),
                ('detail', models.CharField(max_length=255, verbose_name='Деталь')),
                ('defect', models.CharField(max_length=255, verbose_name='Дефект')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Грейд')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('visible_from', models.DateField(verbose_name='Показать с даты')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ktv_defects', to=settings.AUTH_USER_MODEL, verbose_name='Кто отложил')),
            ],
            options={
                'verbose_name': 'Отложенный дефект (KTV)',
                'verbose_name_plural': 'Отложенные дефекты (KTV)',
            },
        ),
    ]
