# Generated by Django 5.1.7 on 2025-09-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_customuser_options_ktvdefect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('controller', 'Контролер'), ('master', 'Мастер'), ('head_area', 'Начальник участка'), ('admin', 'Администратор'), ('qrr_specialist', 'QRR специалист'), ('qrr_supervisor', 'QRR начальник участка'), ('qrr_shift_lead', 'QRR начальник смены'), ('dp', 'Делопроизводитель'), ('uud_controller', 'УУД контролер'), ('uud_master', 'УУД мастер')], default='controller', max_length=20),
        ),
    ]
