# Generated by Django 5.2.4 on 2025-09-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('access_to_the_master_dashboard', 'Доступ к панели мастера'), ('access_to_dp_rvd', 'Доступ к РВД делопроизводителю'), ('access_to_post_of_the_controller', 'Доступ к постам контролера'), ('access_to_the_uud_table', 'Доступ к таблице УУД'), ('access_to_the_marriage_table', 'Доступ к таблице женитьбы'), ('access_to_the_qrr_responsible', 'Доступ к сайту QRR для ответственных'), ('access_to_the_guide', 'Доступ к справочнику'), ('access_to_the_shift_management', 'Доступ к управлению сменой'), ('access_to_the_rvd', 'Доступ к РВД'), ('access_to_the_vqa_data_management', 'Доступ к сайту для управления данными VQA'), ('access_to_the_qrqc_report_vqa', 'Доступ к QRQC отчету VQA'), ('access_to_tracking_by_vin', 'Доступ к отслеживанию по VIN'), ('access_to_pqa_data', 'Доступ к данным PQA'), ('access_to_vqa_data', 'Доступ к данным VQA'), ('access_to_indicators', 'Доступ к показателям'), ('access_to_body_shop_data', 'Доступ к данным Body Shop'), ('show_buttons_to_fi_posts_for_controllers', 'Показ постов первой инспекции контролерам'), ('show_buttons_for_vqa_controllers', 'Показ кнопок для контролеров VQA'), ('show_button_counter_changan', 'Показ кнопки TRIM IN Changan'), ('show_button_counter_chery', 'Показ кнопки TRIM IN Chery'), ('show_button_counter_gwm', 'Показ кнопки TRIM IN GWM'), ('show_button_counter_frame', 'Показ кнопки TRIM IN Frame'), ('show_button_counter_trim_out_changan', 'Показ кнопки TRIM OUT Changan'), ('show_button_counter_trim_out_chery', 'Показ кнопки TRIM OUT Chery'), ('show_button_counter_trim_out_gwm', 'Показ кнопки TRIM OUT GWM'), ('show_button_counter_trim_out_frame', 'Показ кнопки TRIM OUT Frame')]},
        ),
    ]
