# Generated by Django 5.1.7 on 2025-05-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle_history", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "container_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер контейнера"
                    ),
                ),
                (
                    "history",
                    models.JSONField(default=dict, verbose_name="История осмотров"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
        ),
    ]
