# Generated by Django 5.1.7 on 2025-06-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle_history", "0002_containerhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChanganVINHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        max_length=17, unique=True, verbose_name="VIN номер автомобиля"
                    ),
                ),
                (
                    "history",
                    models.JSONField(default=dict, verbose_name="История контроля"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheryVINHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        max_length=17, unique=True, verbose_name="VIN номер автомобиля"
                    ),
                ),
                (
                    "history",
                    models.JSONField(default=dict, verbose_name="История контроля"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VINHistoryBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        max_length=17, verbose_name="VIN номер автомобиля"
                    ),
                ),
                (
                    "post",
                    models.CharField(max_length=255, verbose_name="Название поста"),
                ),
                ("zone", models.CharField(max_length=255, verbose_name="Цех")),
                ("entry", models.JSONField(verbose_name="Удалённая запись")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Когда было удалено"
                    ),
                ),
            ],
        ),
    ]
