# Generated by Django 5.1.7 on 2025-06-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle_history", "0003_changanvinhistory_cheryvinhistory_vinhistorybackup"),
    ]

    operations = [
        migrations.AddField(
            model_name="vinhistorybackup",
            name="action",
            field=models.CharField(
                choices=[("edit", "Изменено"), ("delete", "Удалено")],
                default=1,
                max_length=10,
                verbose_name="Тип действия",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vinhistorybackup",
            name="deleted_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата изменения/удаления"
            ),
        ),
        migrations.AlterField(
            model_name="vinhistorybackup",
            name="entry",
            field=models.JSONField(verbose_name="Содержимое записи"),
        ),
    ]
