# Generated by Django 5.1.7 on 2025-09-04 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_history', '0004_vinhistorybackup_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyPassLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=17, verbose_name='VIN')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда сохранено')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_pass_logs', to=settings.AUTH_USER_MODEL, verbose_name='Кто сохранил')),
            ],
            options={
                'verbose_name': 'Прохождение поста (скан VIN)',
                'verbose_name_plural': 'Прохождения поста (сканы VIN)',
                'indexes': [models.Index(fields=['vin'], name='idx_vin'), models.Index(fields=['scanned_at'], name='idx_scanned_at')],
            },
        ),
    ]
