# Generated by Django 5.1.7 on 2025-09-10 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_history', '0005_assemblypasslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VESPassLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=17, verbose_name='VIN')),
                ('given_at', models.DateTimeField(db_index=True, verbose_name='Дата/время отдачи на VES')),
                ('received_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата/время приёма с VES')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('given_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ves_given_logs', to=settings.AUTH_USER_MODEL, verbose_name='Кто отдал на VES')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ves_received_logs', to=settings.AUTH_USER_MODEL, verbose_name='Кто принял с VES')),
            ],
            options={
                'verbose_name': 'VES: передача/приём VIN',
                'verbose_name_plural': 'VES: передачи/приёмы VIN',
                'indexes': [models.Index(fields=['vin'], name='idx_ves_vin'), models.Index(fields=['given_at'], name='idx_ves_given_at'), models.Index(fields=['received_at'], name='idx_ves_received_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(('received_at__gte', models.F('given_at')), ('received_at__isnull', True), _connector='OR'), name='ves_received_after_given')],
            },
        ),
    ]
