# Generated by Django 5.1.7 on 2025-09-12 02:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_history', '0006_vespasslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblypasslog',
            name='line',
            field=models.CharField(choices=[('gwm', 'GWM'), ('chery', 'Chery'), ('changan', 'Changan')], db_index=True, default=1, max_length=20, verbose_name='Линия сборки'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='assemblypasslog',
            index=models.Index(fields=['line'], name='idx_line'),
        ),
    ]
