# Generated by Django 5.1.7 on 2025-09-21 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_history', '0007_assemblypasslog_line_assemblypasslog_idx_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrimOutPassLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=17, verbose_name='VIN')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда сохранено')),
                ('line', models.CharField(choices=[('gwm', 'GWM'), ('chery', 'Chery'), ('changan', 'Changan'), ('frame', 'Frame')], db_index=True, max_length=20, verbose_name='Линия сборки')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trimout_pass_logs', to=settings.AUTH_USER_MODEL, verbose_name='Кто сохранил')),
            ],
            options={
                'verbose_name': 'TRIM OUT (скан VIN)',
                'verbose_name_plural': 'TRIM OUT (сканы VIN)',
                'indexes': [models.Index(fields=['vin'], name='idx_trimout_vin'), models.Index(fields=['scanned_at'], name='idx_trimout_scanned_at'), models.Index(fields=['line'], name='idx_trimout_line')],
            },
        ),
    ]
