# Generated by Django 5.2.4 on 2025-09-24 07:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_history', '0008_trimoutpasslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimoutpasslog',
            name='scanned_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Когда сохранено'),
        ),
        migrations.CreateModel(
            name='VehicleIdentifiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=17, unique=True, verbose_name='VIN код')),
                ('engine_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Номер двигателя')),
                ('transmission_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Номер трансмиссии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда сохранили')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Когда обновлена запись')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_vehicle_identifiers', to=settings.AUTH_USER_MODEL, verbose_name='Кто сохранил')),
            ],
            options={
                'verbose_name': 'Идентификаторы автомобиля',
                'verbose_name_plural': 'Идентификаторы автомобилей',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['vin'], name='vehicle_his_vin_900174_idx')],
            },
        ),
    ]
