"""
Django settings for factory_server project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")



BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "changeme-please-set-DJANGO_SECRET_KEY")
DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost").split(",") if h.strip()]

SECURE_SSL_REDIRECT = os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "True").lower() in ("1", "true", "yes")


if DEBUG:
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
else:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django_extensions',

    'users',
    'supplies',
    "vehicle_history.apps.VehicleHistoryConfig",
    'assembly',
    'qrr',
    'public_directory',
    'administrators',
    "line_stats",

    'channels',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'administrators.middleware.ActivityLoggingMiddleware',
]

ROOT_URLCONF = "factory_server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = 'factory_server.asgi.application'
WSGI_APPLICATION = "factory_server.wsgi.application"


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
            "capacity": 1000,
            "expiry": 10,
            "group_expiry": 3600,
        },
    }
}


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
        },
        "TIMEOUT": 60,
    }
}


SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"


DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DJANGO_DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.environ.get("DJANGO_DB_NAME", "factory_db"),
        "USER": os.environ.get("DJANGO_DB_USER", "factory_user"),
        "PASSWORD": os.environ.get("DJANGO_DB_PASSWORD", ""),
        "HOST": os.environ.get("DJANGO_DB_HOST", "localhost"),
        "PORT": os.environ.get("DJANGO_DB_PORT", "5432"),
        "CONN_MAX_AGE": int(os.environ.get("DJANGO_DB_CONN_MAX_AGE", "300")),
        # при необходимости добавьте другие опции
    }
}

EMAIL_BACKEND = os.environ.get("DJANGO_EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("DJANGO_EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("DJANGO_EMAIL_USE_TLS", "True").lower() in ("1", "true", "yes")
EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DJANGO_DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@example.com")


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


CSRF_TRUSTED_ORIGINS = [
    'https://127.0.0.1',
    'http://127.0.0.1',
    'https://localhost',
    'http://localhost',
    'https://10.85.176.87',
    'http://10.85.176.87',
    'https://qd-ammk.com',
]

LANGUAGE_CODE = "ru"

TIME_ZONE = "Asia/Almaty"

USE_I18N = True

USE_TZ = True

STATIC_URL = "/static/"
MEDIA_URL = "/media/"
STATIC_ROOT = os.environ.get("DJANGO_STATIC_ROOT", os.path.join(BASE_DIR, "staticfiles"))
MEDIA_ROOT = os.environ.get("DJANGO_MEDIA_ROOT", os.path.join(BASE_DIR, "media"))

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'users.CustomUser'

LOGIN_REDIRECT_URL = '/users/dashboard/'


LOGIN_URL = '/users/login/'

CSRF_FAILURE_VIEW = 'users.views.csrf_failure'


DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000



JAZZMIN_SETTINGS = {
    "site_title": "QD AMMK — Admin",
    "site_header": "QD AMMK",
    "welcome_sign": "Панель качества",
    "copyright": "AMMK",

    "show_sidebar": True,
    "navigation_expanded": False,
    "hide_apps": [],
    "hide_models": [],

    "order_with_respect_to": ["assembly", "qrr", "supplies", "users", "vehicle_history", "administrators"],

    "icons": {
        "assembly": "fas fa-cogs",
        "supplies": "fas fa-boxes",
        "qrr": "fas fa-search",
        "users": "fas fa-users",
        "vehicle_history": "fas fa-car",
        "administrators": "fas fa-user-shield",
    },

    "side_menu": [
        {"app": "assembly", "label": "ASSEMBLY", "icon": "fas fa-cogs"},
        {"app": "qrr", "label": "QRR", "icon": "fas fa-search"},
        {"app": "supplies", "label": "SUPPLIES", "icon": "fas fa-boxes"},
        {"app": "users", "label": "USERS", "icon": "fas fa-users"},
        {"app": "vehicle_history", "label": "VEHICLE HISTORY", "icon": "fas fa-car"},
        {"app": "administrators", "label": "ADMINISTRATORS", "icon": "fas fa-user-shield"},
    ],
}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "sidebar": "sidebar-dark-primary",
    "sidebar_fixed": True,
    "navbar": "navbar-dark",
    "navbar_fixed": True,
    "actions_sticky_top": True,
    "sidebar_nav_compact_style": True,
}
