"""
Django settings for factory_server project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

os.environ.setdefault("PGCLIENTENCODING", "UTF8")

REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-kd#895k!2rm=3^e0nbz(@06%g+@1x%^cn_x(igj_-2+*toxx*b"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['10.85.131.92', 'qd-ammk.com', '127.0.0.1', '10.85.178.229']
SECURE_SSL_REDIRECT = False
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_HSTS_SECONDS = 31536000  # 1 год
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django_extensions',

    'users',
    'supplies',
    "vehicle_history.apps.VehicleHistoryConfig",
    'assembly',
    'qrr',
    'public_directory',
    'administrators',
    "line_stats",

    'channels',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'administrators.middleware.ActivityLoggingMiddleware',
]

ROOT_URLCONF = "factory_server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = 'factory_server.asgi.application'
WSGI_APPLICATION = "factory_server.wsgi.application"


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
            "capacity": 1000,
            "expiry": 10,
            "group_expiry": 3600,
        },
    }
}


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
        },
        "TIMEOUT": 60,
    }
}


SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"


# Database54
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'factory_db',
        'USER': 'factory_user',
        'PASSWORD': '@lidacain174',
        'HOST': 'localhost',
        'PORT': '5432',
        'CONN_MAX_AGE': 300,          # реже реконнекты
        'CONN_HEALTH_CHECKS': True,   # проверка «живости» коннекта перед использованием
        'OPTIONS': {
            'options': '-c client_encoding=UTF8',  # ключевое для твоей ошибки
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


CSRF_TRUSTED_ORIGINS = [
    'https://127.0.0.1',
    'https://localhost',
    'https://10.85.176.87',
    'https://qd-ammk.com',
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "Asia/Almaty"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

import os
from pathlib import Path

# --- Static files ---
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')  # ← это твоя "исходная" папка
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # ← сюда будет собираться

# --- Media files ---
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'users.CustomUser'

GOOGLE_SHEETS_CREDENTIALS_PATH = os.path.join(BASE_DIR, "daring-hash-403304-f75ea5c718bb.json")

LOGIN_REDIRECT_URL = '/users/dashboard/'


LOGIN_URL = '/users/login/'

CSRF_FAILURE_VIEW = 'users.views.csrf_failure'


DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000



# Jazzmin configuration
JAZZMIN_SETTINGS = {
    "site_title": "QD AMMK — Admin",
    "site_header": "QD AMMK",
    "welcome_sign": "Панель качества",
    "copyright": "AMMK",

    "show_sidebar": True,
    "navigation_expanded": False,
    "hide_apps": [],
    "hide_models": [],

    "order_with_respect_to": ["assembly", "qrr", "supplies", "users", "vehicle_history", "administrators"],

    "icons": {
        "assembly": "fas fa-cogs",
        "supplies": "fas fa-boxes",
        "qrr": "fas fa-search",
        "users": "fas fa-users",
        "vehicle_history": "fas fa-car",
        "administrators": "fas fa-user-shield",
    },

    "side_menu": [
        {"app": "assembly", "label": "ASSEMBLY", "icon": "fas fa-cogs"},
        {"app": "qrr", "label": "QRR", "icon": "fas fa-search"},
        {"app": "supplies", "label": "SUPPLIES", "icon": "fas fa-boxes"},
        {"app": "users", "label": "USERS", "icon": "fas fa-users"},
        {"app": "vehicle_history", "label": "VEHICLE HISTORY", "icon": "fas fa-car"},
        {"app": "administrators", "label": "ADMINISTRATORS", "icon": "fas fa-user-shield"},
    ],
}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "sidebar": "sidebar-dark-primary",
    "sidebar_fixed": True,
    "navbar": "navbar-dark",
    "navbar_fixed": True,
    "actions_sticky_top": True,
    "sidebar_nav_compact_style": True,
}
