# Generated by Django 5.1.7 on 2025-09-18 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorsWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(related_name='line_stats_editors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Допущенные редакторы',
                'verbose_name_plural': 'Допущенные редакторы',
            },
        ),
        migrations.CreateModel(
            name='HourlyLineStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('line', models.CharField(choices=[('gwm', 'GWM'), ('chery', 'CHERY'), ('changan', 'CHANGAN'), ('frame', 'FRAME LINE'), ('pdi', 'PDI')], db_index=True, max_length=16)),
                ('shift', models.CharField(choices=[('s1', 'Первая смена'), ('s2', 'Вторая смена')], db_index=True, default='s1', max_length=2)),
                ('start', models.TimeField(db_index=True)),
                ('end', models.TimeField(db_index=True)),
                ('plan_snapshot', models.PositiveIntegerField(default=0)),
                ('actual', models.PositiveIntegerField(default=0)),
                ('downtime_min', models.PositiveIntegerField(default=0)),
                ('downtime_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reason_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_stats_reason_authors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Факт по часу (финал)',
                'verbose_name_plural': 'Факты по часам (финал)',
                'ordering': ('date', 'line', 'shift', 'start'),
                'unique_together': {('date', 'line', 'shift', 'start', 'end')},
            },
        ),
        migrations.CreateModel(
            name='HourlyPDIStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('shift', models.CharField(choices=[('s1', 'Первая смена'), ('s2', 'Вторая смена')], db_index=True, default='s1', max_length=2)),
                ('start', models.TimeField(db_index=True)),
                ('end', models.TimeField(db_index=True)),
                ('in_count', models.PositiveIntegerField(default=0, help_text='Сколько машин вошло в PDI за час')),
                ('out_count', models.PositiveIntegerField(default=0, help_text='Сколько машин вышло из PDI за час')),
                ('wip_count', models.PositiveIntegerField(default=0, help_text='Сколько машин находятся в PDI на конец часа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статистика PDI по часу',
                'verbose_name_plural': 'Статистика PDI по часам',
                'ordering': ('date', 'shift', 'start'),
                'unique_together': {('date', 'shift', 'start', 'end')},
            },
        ),
        migrations.CreateModel(
            name='HourlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(choices=[('gwm', 'GWM'), ('chery', 'CHERY'), ('changan', 'CHANGAN'), ('frame', 'FRAME LINE'), ('pdi', 'PDI')], db_index=True, max_length=16)),
                ('shift', models.CharField(choices=[('s1', 'Первая смена'), ('s2', 'Вторая смена')], db_index=True, default='s1', max_length=2)),
                ('start', models.TimeField(db_index=True)),
                ('end', models.TimeField(db_index=True)),
                ('effective_from', models.DateField(db_index=True, help_text='Дата, с которой этот план действует')),
                ('value', models.PositiveIntegerField(default=0, help_text='Сколько машин должно пройти в этот час')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'План по часу',
                'verbose_name_plural': 'Планы по часам',
                'ordering': ('line', 'shift', 'start', '-effective_from'),
                'unique_together': {('line', 'shift', 'start', 'end', 'effective_from')},
            },
        ),
    ]
