# Generated by Django 5.1.5 on 2025-02-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContainerUnloadingZone2Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "container_number",
                    models.CharField(max_length=20, verbose_name="Номер контейнера"),
                ),
                (
                    "pallet_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Номер палета",
                    ),
                ),
                (
                    "defect_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание дефекта"
                    ),
                ),
                (
                    "container_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/containers/",
                        verbose_name="Фото контейнера",
                    ),
                ),
                (
                    "pallet_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/pallets/",
                        verbose_name="Фото палета",
                    ),
                ),
                (
                    "defect_images",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Фото дефекта (список URL через запятую)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата фиксации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Зона выгрузки контейнеров, этаж 2 (Инспекция)",
                "verbose_name_plural": "Зона выгрузки контейнеров, этаж 2 (Инспекции)",
            },
        ),
        migrations.CreateModel(
            name="Defect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название дефекта"
                    ),
                ),
            ],
            options={
                "verbose_name": "Дефект",
                "verbose_name_plural": "Дефекты",
            },
        ),
        migrations.CreateModel(
            name="Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название детали"
                    ),
                ),
            ],
            options={
                "verbose_name": "Деталь",
                "verbose_name_plural": "Детали",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название поста"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Местоположение",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
