# Generated by Django 5.1.5 on 2025-02-17 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("supplies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="containerunloadingzone2inspection",
            name="controller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Контроллер",
            ),
        ),
        migrations.AddField(
            model_name="containerunloadingzone2inspection",
            name="defect",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="supplies.defect",
                verbose_name="Дефект",
            ),
        ),
        migrations.AddField(
            model_name="containerunloadingzone2inspection",
            name="detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="supplies.detail",
                verbose_name="Деталь",
            ),
        ),
        migrations.AddField(
            model_name="detail",
            name="posts",
            field=models.ManyToManyField(
                related_name="details", to="supplies.post", verbose_name="Посты"
            ),
        ),
        migrations.AddField(
            model_name="defect",
            name="posts",
            field=models.ManyToManyField(
                related_name="defects", to="supplies.post", verbose_name="Посты"
            ),
        ),
        migrations.AddField(
            model_name="containerunloadingzone2inspection",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="supplies.post",
                verbose_name="Пост",
            ),
        ),
    ]
