# Generated by Django 5.1.5 on 2025-02-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerUnloadingZoneSBInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=20, verbose_name='Номер контейнера')),
                ('container_images', models.TextField(blank=True, null=True, verbose_name='Фото контейнера (список URL через запятую)')),
                ('container_number_image', models.ImageField(blank=True, null=True, upload_to='images/container_numbers/', verbose_name='Фото номера контейнера')),
                ('container_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание контейнера')),
                ('seal_image', models.ImageField(blank=True, null=True, upload_to='images/container_seals/', verbose_name='Фото пломбы контейнера')),
                ('seal_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание пломбы')),
                ('container_status', models.CharField(choices=[('damaged', 'Контейнер поврежден'), ('not_damaged', 'Контейнер не поврежден')], max_length=20, verbose_name='Состояние контейнера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата фиксации')),
            ],
            options={
                'verbose_name': 'Зона выгрузки контейнеров SB (Инспекция)',
                'verbose_name_plural': 'Зона выгрузки контейнеров SB (Инспекции)',
            },
        ),
    ]
