# Generated by Django 5.1.5 on 2025-02-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0003_containerunloadingzonesbinspection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="containerunloadingzone2inspection",
            name="defect_description",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Описание дефекта"
            ),
        ),
    ]
