# Generated by Django 5.1.5 on 2025-02-19 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0004_alter_containerunloadingzone2inspection_defect_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="containerunloadingzonesbinspection",
            name="controller",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Контроллер",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="containerunloadingzonesbinspection",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="supplies.post",
                verbose_name="Пост",
            ),
            preserve_default=False,
        ),
    ]
