# Generated by Django 5.1.5 on 2025-02-24 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0005_containerunloadingzonesbinspection_controller_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_code",
                    models.CharField(max_length=50, verbose_name="Configuration Code"),
                ),
                (
                    "body_number",
                    models.CharField(max_length=50, verbose_name="Body Number"),
                ),
                ("vin_rk", models.CharField(max_length=50, verbose_name="VIN RK")),
                ("vin_c", models.CharField(max_length=50, verbose_name="VIN C")),
                (
                    "engine_number",
                    models.CharField(max_length=50, verbose_name="Engine Number"),
                ),
                ("engine_volume", models.IntegerField(verbose_name="Engine Volume")),
                (
                    "modification",
                    models.CharField(max_length=50, verbose_name="Modification"),
                ),
                (
                    "body_color",
                    models.CharField(max_length=50, verbose_name="Body Color"),
                ),
                (
                    "transmission",
                    models.CharField(max_length=50, verbose_name="Transmission"),
                ),
                (
                    "engine_power",
                    models.CharField(
                        max_length=50, verbose_name="Engine Power (hp/kW)"
                    ),
                ),
                ("gross_weight", models.IntegerField(verbose_name="Gross Weight")),
                ("weight", models.IntegerField(verbose_name="Weight")),
                (
                    "config_code_extra",
                    models.CharField(
                        max_length=50, verbose_name="Additional Configuration Code"
                    ),
                ),
                (
                    "color_1c",
                    models.CharField(max_length=50, verbose_name="Color in 1C"),
                ),
                (
                    "body_type",
                    models.CharField(max_length=50, verbose_name="Body Type"),
                ),
                ("seat_capacity", models.IntegerField(verbose_name="Seating Capacity")),
                (
                    "production_year",
                    models.IntegerField(verbose_name="Production Year"),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date Added"
                    ),
                ),
            ],
            options={
                "verbose_name": "Trace Data",
                "verbose_name_plural": "Trace Data",
            },
        ),
    ]
