# Generated by Django 5.1.5 on 2025-02-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0006_tracedata"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracedata",
            name="brand",
            field=models.CharField(default=1, max_length=50, verbose_name="Brand"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tracedata",
            name="model",
            field=models.CharField(default=1, max_length=50, verbose_name="Model"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tracedata",
            name="vin_rk",
            field=models.CharField(max_length=50, unique=True, verbose_name="VIN RK"),
        ),
    ]
