# Generated by Django 5.1.5 on 2025-02-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0007_tracedata_brand_tracedata_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracedata",
            name="brand",
            field=models.CharField(
                default="Unknown", max_length=50, verbose_name="Brand"
            ),
        ),
        migrations.AlterField(
            model_name="tracedata",
            name="model",
            field=models.CharField(
                default="Unknown", max_length=50, verbose_name="Model"
            ),
        ),
    ]
