# Generated by Django 5.1.5 on 2025-02-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0008_alter_tracedata_brand_alter_tracedata_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefectGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Грейд дефекта"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание грейда"
                    ),
                ),
            ],
            options={
                "verbose_name": "Грейд дефекта",
                "verbose_name_plural": "Грейды дефектов",
            },
        ),
        migrations.CreateModel(
            name="DefectResponsible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Ответственный за дефект",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Цех / Отдел",
                    ),
                ),
                (
                    "posts",
                    models.ManyToManyField(
                        related_name="defect_responsibles",
                        to="supplies.post",
                        verbose_name="Посты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответственный за дефект",
                "verbose_name_plural": "Ответственные за дефекты",
            },
        ),
    ]
