# Generated by Django 5.1.7 on 2025-04-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0009_defectgrade_defectresponsible"),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название детали"
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("left", "Левая сторона"),
                            ("right", "Правая сторона"),
                            ("front", "Передняя часть"),
                            ("back", "Задняя часть"),
                            ("up", "Верх"),
                            ("all", "Все зоны (Прочее)"),
                        ],
                        max_length=10,
                        verbose_name="Часть кузова",
                    ),
                ),
                (
                    "posts",
                    models.ManyToManyField(
                        related_name="body_details",
                        to="supplies.post",
                        verbose_name="Посты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Деталь кузова",
                "verbose_name_plural": "Детали кузова",
            },
        ),
    ]
