# Generated by Django 5.1.7 on 2025-06-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0010_bodydetail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bodydetail",
            options={
                "verbose_name": "Деталь кузова/интерьера",
                "verbose_name_plural": "Детали кузова и интерьера",
            },
        ),
        migrations.AlterField(
            model_name="bodydetail",
            name="zone",
            field=models.CharField(
                choices=[
                    ("left", "Левая сторона"),
                    ("right", "Правая сторона"),
                    ("front", "Передняя часть"),
                    ("back", "Задняя часть"),
                    ("up", "Верх"),
                    ("all", "Все зоны (Прочее)"),
                    ("mult", "Мультимедиа"),
                    ("salon", "Салон"),
                    ("fd_right", "Дверь передняя правая"),
                    ("fd_left", "Дверь передняя левая"),
                    ("bd_right", "Дверь задняя правая"),
                    ("bd_left", "Дверь задняя левая"),
                ],
                max_length=20,
                verbose_name="Часть кузова/интерьера",
            ),
        ),
    ]
