# Generated by Django 5.1.7 on 2025-09-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0011_alter_bodydetail_options_alter_bodydetail_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracedata',
            name='interior_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Interior Color'),
        ),
    ]
