# Generated by Django 5.1.7 on 2025-09-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0012_tracedata_interior_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracedata',
            name='tdmm_front_axle',
            field=models.IntegerField(blank=True, null=True, verbose_name='ТДММ на переднюю ось (кг)'),
        ),
        migrations.AddField(
            model_name='tracedata',
            name='tdmm_rear_axle',
            field=models.IntegerField(blank=True, null=True, verbose_name='ТДММ на заднюю ось (кг)'),
        ),
    ]
