# Generated by Django 5.2.4 on 2025-09-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0013_tracedata_tdmm_front_axle_tracedata_tdmm_rear_axle'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracedata',
            name='butch_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер батча'),
        ),
    ]
