# Generated by Django 5.1.7 on 2025-06-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrators", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylog",
            name="url",
            field=models.URLField(max_length=1000),
        ),
    ]
