# Generated by Django 5.1.5 on 2025-03-13 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MountingPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название крепления"),
                ),
                (
                    "modification",
                    models.CharField(
                        choices=[("2WD", "2WD"), ("4WD", "4WD")],
                        max_length=3,
                        verbose_name="Модификация",
                    ),
                ),
                ("size", models.CharField(max_length=50, verbose_name="Размер")),
                ("quantity", models.IntegerField(verbose_name="Количество")),
                ("torque", models.FloatField(verbose_name="Момент затяжки (Нм)")),
            ],
        ),
        migrations.CreateModel(
            name="PostAssembly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Название поста (сборка)",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Местоположение (сборка)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост (сборка)",
                "verbose_name_plural": "Посты (сборка)",
            },
        ),
        migrations.CreateModel(
            name="AssemblyPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название узла/детали"
                    ),
                ),
                ("size", models.CharField(max_length=50, verbose_name="Размер")),
                ("quantity", models.IntegerField(verbose_name="Количество")),
                ("torque", models.FloatField(verbose_name="Момент затяжки (Нм)")),
                (
                    "mounting_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assembly.mountingpoint",
                        verbose_name="Крепление",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DefectAssembly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Название дефекта (сборка)",
                    ),
                ),
                (
                    "posts",
                    models.ManyToManyField(
                        related_name="defects",
                        to="assembly.postassembly",
                        verbose_name="Посты (сборка)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дефект (сборка)",
                "verbose_name_plural": "Дефекты (сборка)",
            },
        ),
    ]
