# Generated by Django 5.1.5 on 2025-03-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assembly", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assemblypart",
            options={
                "verbose_name": "Узел/Деталь (сборка)",
                "verbose_name_plural": "Узлы/Детали (сборка)",
            },
        ),
        migrations.AlterModelOptions(
            name="mountingpoint",
            options={
                "verbose_name": "Крепление (сборка)",
                "verbose_name_plural": "Крепления (сборка)",
            },
        ),
        migrations.RemoveField(
            model_name="assemblypart",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="assemblypart",
            name="torque",
        ),
        migrations.RemoveField(
            model_name="mountingpoint",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="mountingpoint",
            name="size",
        ),
        migrations.RemoveField(
            model_name="mountingpoint",
            name="torque",
        ),
        migrations.AddField(
            model_name="assemblypart",
            name="max_quantity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Максимальное количество"
            ),
        ),
        migrations.AddField(
            model_name="assemblypart",
            name="max_torque",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Максимальный момент затяжки (Нм)"
            ),
        ),
        migrations.AddField(
            model_name="assemblypart",
            name="min_quantity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Минимальное количество"
            ),
        ),
        migrations.AddField(
            model_name="assemblypart",
            name="min_torque",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Минимальный момент затяжки (Нм)"
            ),
        ),
    ]
