# Generated by Django 5.1.5 on 2025-03-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assembly", "0002_alter_assemblypart_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assemblypart",
            name="mounting_point",
        ),
        migrations.AddField(
            model_name="assemblypart",
            name="modification",
            field=models.CharField(
                choices=[("2WD", "2WD"), ("4WD", "4WD")],
                default="2WD",
                max_length=3,
                verbose_name="Модификация",
            ),
        ),
        migrations.DeleteModel(
            name="MountingPoint",
        ),
    ]
