# Generated by Django 5.1.7 on 2025-06-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assembly", "0003_remove_assemblypart_mounting_point_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssemblyDefect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Название дефекта (сборка)",
                    ),
                ),
                (
                    "nameENG",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Defect name (ENG)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дефект (справочник сборка)",
                "verbose_name_plural": "Дефекты (справочник сборка)",
            },
        ),
        migrations.CreateModel(
            name="AssemblyDefectGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Грейд дефекта (сборка)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание грейда (сборка)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Грейд дефекта (сборка)",
                "verbose_name_plural": "Грейды дефектов (сборка)",
            },
        ),
        migrations.CreateModel(
            name="AssemblyUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Название узла (справочник сборка)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Узел (справочник сборка)",
                "verbose_name_plural": "Узлы (справочник сборка)",
            },
        ),
        migrations.CreateModel(
            name="AssemblyDefectResponsible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Ответственный за дефект (сборка)",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Цех / Отдел (сборка)",
                    ),
                ),
                (
                    "posts",
                    models.ManyToManyField(
                        related_name="defect_responsibles_assembly",
                        to="assembly.postassembly",
                        verbose_name="Посты (сборка)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответственный за дефект (сборка)",
                "verbose_name_plural": "Ответственные за дефекты (сборка)",
            },
        ),
    ]
