# Generated by Django 5.1.7 on 2025-08-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assembly", "0004_assemblydefect_assemblydefectgrade_assemblyunit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assemblyunit",
            name="zone",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Зона/группа узла"
            ),
        ),
    ]
