# Generated by Django 5.1.7 on 2025-08-13 07:25

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0005_assemblyunit_zone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assemblyunit',
            options={'verbose_name': 'Детали (сборка)', 'verbose_name_plural': 'Детали(сборка)'},
        ),
        migrations.AddField(
            model_name='assemblydefect',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='assembly_defects', to='assembly.postassembly', verbose_name='Посты'),
        ),
        migrations.AddField(
            model_name='assemblyunit',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='assembly_units', to='assembly.postassembly', verbose_name='Посты'),
        ),
        migrations.AlterField(
            model_name='assemblyunit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название узла (сборка)'),
        ),
        migrations.CreateModel(
            name='AssemblyZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название зоны')),
                ('posts', models.ManyToManyField(blank=True, related_name='assembly_zones', to='assembly.postassembly', verbose_name='Посты')),
            ],
            options={
                'verbose_name': 'Подсистема (зона сборки)',
                'verbose_name_plural': 'Подсистемы сборки',
            },
        ),
        migrations.AlterField(
            model_name='assemblyunit',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assembly.assemblyzone', verbose_name='Зона/группа узла'),
        ),
        migrations.AddConstraint(
            model_name='assemblyunit',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('zone'), name='uniq_unit_name_per_zone_ci'),
        ),
    ]
