# Generated by Django 5.1.7 on 2025-05-02 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicle_history", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QRRInvestigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_number", models.CharField(max_length=20, unique=True)),
                (
                    "form_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата заполнения формы"
                    ),
                ),
                (
                    "form_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время заполнения формы"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "performed_by_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Выполнил (вручную)"
                    ),
                ),
                (
                    "confirmed_by_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Подтвердил (вручную)"
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[("day", "Дневная"), ("night", "Ночная")], max_length=20
                    ),
                ),
                ("inspector", models.CharField(max_length=100)),
                ("confirmed_tl_sv", models.CharField(blank=True, max_length=100)),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("station", models.CharField(max_length=100)),
                ("vin", models.CharField(max_length=50)),
                ("grade", models.CharField(max_length=10)),
                ("defect_text", models.TextField()),
                ("inspection_standard", models.TextField(blank=True)),
                ("check_method", models.CharField(blank=True, max_length=255)),
                ("value", models.CharField(blank=True, max_length=100)),
                ("standard_criteria", models.TextField(blank=True)),
                ("qtf_nominal", models.CharField(blank=True, max_length=100)),
                ("defect_description", models.TextField(blank=True)),
                (
                    "defect_photo",
                    models.ImageField(blank=True, null=True, upload_to="qrr/defects/"),
                ),
                ("repair_method", models.TextField(blank=True)),
                (
                    "car_checked_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("ng_count", models.PositiveIntegerField(blank=True, null=True)),
                ("checklist_number", models.CharField(blank=True, max_length=100)),
                ("temporary_measure", models.TextField(blank=True)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("conclusion", models.TextField(blank=True)),
                ("crcr_number", models.CharField(blank=True, max_length=100)),
                ("ktm_number", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершено"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "confirmed_by_user",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "role__in": ["qrr_supervisor", "qrr_shift_lead"]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_qrr",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Подтвердил (из пользователей)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_investigations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performed_by_user",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "role__in": [
                                "qrr_specialist",
                                "qrr_supervisor",
                                "qrr_shift_lead",
                            ]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_qrr",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Выполнил (из пользователей)",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_investigations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vin_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investigations",
                        to="vehicle_history.vinhistory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvestigationResponsibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("factor", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("full_name", models.CharField(max_length=100)),
                ("crcr_number", models.CharField(blank=True, max_length=100)),
                ("ktm_number", models.CharField(blank=True, max_length=100)),
                ("comment", models.TextField(blank=True)),
                (
                    "investigation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsibilities",
                        to="qrr.qrrinvestigation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvestigationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("factor", models.CharField(max_length=100)),
                ("action", models.TextField()),
                ("responsible", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("result", models.TextField()),
                (
                    "investigation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="qrr.qrrinvestigation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvestigationFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "investigation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factors",
                        to="qrr.qrrinvestigation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FactorCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("factor_text", models.CharField(max_length=255)),
                ("check_method", models.CharField(max_length=255)),
                ("responsible", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("comment", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="qrr/factor_checks/"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("OK", "ОК"), ("NG", "NG")], max_length=2
                    ),
                ),
                ("factor_type", models.CharField(blank=True, max_length=100)),
                (
                    "investigation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factor_checks",
                        to="qrr.qrrinvestigation",
                    ),
                ),
            ],
        ),
    ]
