# Generated by Django 5.1.7 on 2025-09-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRRResponsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Ответственный (QRR)',
                'verbose_name_plural': 'Ответственные (QRR)',
            },
        ),
    ]
